#!/bin/bash

## Description: Install Drupal and enable the module
## Usage: install
## Example: "ddev install"

vendor/bin/drush site:install --yes
vendor/bin/drush pm:install oe_ai_provider_gpt_at_ec --yes
